language: bash
install:
  - git clone -b 'v0.0.6' --single-branch --depth 1 git://github.com/bmizerany/roundup.git /tmp/roundup
  - cd /tmp/roundup
  - ./configure --development && make
  - cd -
script:
  - /tmp/roundup/roundup tests/*
