#!/usr/bin/env bash

describe "Composer Transfer Features Tests"

# Generic single file wrokflow.
it_check_sigle_file_upload() {
  usage=$(echo 'upload' > testfile.txt && ./transfer testfile.txt | head -n 1);
  rm testfile.txt;
  curl -0 $usage > downloaded.txt;
  test `cat downloaded.txt` = 'upload';
  rm downloaded.txt;
}

# Pipeline single file wrokflow.
it_check_work_with_pipe() {
  usage=$(echo 'pipeline' > testfile.txt && cat testfile.txt | ./transfer newname.txt | head -n 1);
  rm testfile.txt;
  curl -0 $usage > downloaded.txt;
  test `cat downloaded.txt` = 'pipeline';
  rm downloaded.txt;
}

# Testing folders support.
it_check_work_with_folders() {
  mkdir test;
  echo 'ziptest' > test/test.txt;
  usage=$(./transfer test | head -n 1);
  rm -rf test;
  curl -0 $usage > downloaded.zip;
  unzip downloaded.zip;
  test `cat test/test.txt` = 'ziptest';
  rm -rf test downloaded.zip;
}
